site_name: 猫屎加速
site_url: https://catpooo.github.io/

theme:
  name: material
  palette:
    - scheme: default
      primary: white

  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - search.suggest
    - search.highlight

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+i__hJPORw2I3NzA9

copyright: Copyright &copy; 2023 猫屎加速

extra_css:
  - stylesheets/extra.css

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav:
            - 猫屎加速: index.md
            - 文档: docs/Installation.md
            - Terms Of Service: docs/TermsOfService.md
            - Privacy Policy: docs/Privacy.zh.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Docs: docs/Installation.md
  - Terms Of Service: docs/TermsOfService.md
  - Privacy Policy: docs/Privacy.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
